# ===============================
# CONFIGURACIONES DE SISTEMA
# Devs: Agrada Rodriguez Kevin
#		Huarina Condori Viviana
#		Cuellar Antequera Daniel
#		Sirpa Quispe Talia
# ===============================
spring.application.name=magri-backend
# ===============================
# Configuración de la Base de Datos
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_incidencias
spring.datasource.username=postgres
spring.datasource.password=Pa$$w0rd
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Configuración de JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Puerto del servidor
# ===============================
server.port=8081
